apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    #backstage.io/techdocs-ref: url:https://github.com/org-name/repo-name
spec:
  type: website
  lifecycle: development
  owner: ${{values.owner | dump}}
